### ISSUE TITLE
I'm very interested in this. What's the ETA?

### ISSUE THREAD

**Issue by majhork** [gcanti/babel-plugin-tcomb#1]
Also do you intend to parse union and intersection types?

**Comment by gcanti** [comment]
Hi,
it's difficult to say at the moment. For now I'm just playing with babel's plugin APIs.
Luckily there is a plugin which I can take as reference implementation:

https://github.com/codemix/babel-plugin-typecheck

**Comment by zerkalica** [comment]
Why not to parse flowtypes to tcombtypes for run-time checking?

**Comment by majhork** [comment]
Flow provides static checking for Flow types. Otherwise converting those types to tcomb and preserving the unions and intersections would allow *very* interesting introspective capabilities. I imagine you could get autocomplete and light ide support by adding some very light hacks.

**Comment by zerkalica** [comment]
In https://github.com/codemix/babel-plugin-typecheck/issues/21#issuecomment-144724291 i try to describe some problems about runtime checking reflection and external libraries.

**Comment by gcanti** [comment]
Hi all,
So I wrote the basic code in order to handle the main constructs of tcomb [README](https://github.com/gcanti/babel-plugin-tcomb/blob/master/README.md).
It's already usable but now I wonder if this plugin should handle Flow types and convert them to corresponding tcomb types:

- `string` -> `t.String`
- `number` -> `t.Number`
- `boolean` -> `t.Boolean`
- `Array` -> `t.Array`
- `Function` -> `t.Function`
- `Object` -> `t.Object`
- `any`, `mixed` -> `t.Any`

As example the following function:

```js
function sum(x: number, y: ?number): number {
  return x + (y || 0);
}
```

will be compiled by the plugin to something like:

```js
function sum(x: number, y: ?number): number {
  x = t.Number(x);
  y = t.maybe(t.Number)(y);

  const ret = function (x, y) {
    return x + (y || 0);
  }(x, y);

  return t.Number(ret);
}
```

**Comment by Chrisui** [comment]
I would love to see the basic flow types be implemented (ie. moving towards something like the intention of your `flowcheck` library.

Would be interesting to discuss how to implement the more complex types such as the flow equivilent of a `Struct` etc.

**Comment by gcanti** [comment]
Converting the basic Flow types to tcomb should be straightforward. The main problem is that AFAIK Flow can't understand structs, just classes and Object types. This weekend I'm going to play with Flow v0.17, maybe I can find something new/useful.

> Maybe parsing Object type declarations look good for struct's?

It depends on your goal. If you want to preserve the Flow semantic I should add a new combinator: Object types are structural while structs are "nominal" (they use `instanceof` internally). Moreover I should handle classes, now this would raise an error:

```js
class A {}

function f(a: A) {
  return a;
}

f(new A());
```

since the plugin will convert `f` to something like:

```js
function f(a: A) {
  a = A(a); // all tcomb types are glorified identity functions

  return a;
}
```

**Comment by majhork** [comment]
Could you not compile to this instead?
~~~ js
t.Function([t.Number, t.maybe(t.Number)], t.Number).of(
    function sum(x: number, y: ?number): number {
        return x + (y || 0);
    }
);
~~~
I can see some potential problems but it would be really nice to get runtime type information for functions.

**Comment by Chrisui** [comment]
Ah. Had no idea Structs were nominal in this case. Still a bit naive about types and such so bear with me :)

For my use case I am after structural typing. We have no classes but just pass around state as immutable objects.

NB: A lot of what I *want* to do in the future is currently being inspired by the F# ["design with types"](http://fsharpforfunandprofit.com/posts/designing-with-types-intro/) series which you're probably familiar with. `tcomb` basically does the runtime side of this dynamically but I'm trying to find a way to bend Flow to offer the static side we need which I think is *almost* there.

**Comment by ivan-kleshnin** [comment]
What's the current status of this? If Tcomb syntax is Flow-compatible can we have **both** sides of the coin (static type checking + first-class types)?

P.S.

Readme does not mention that "syntax-flow" and "transform-flow-strip-types" plugins are required to run.

**Comment by gcanti** [comment]
> What's the current status of this?

Only tcomb types are supported. i.e this is ok:

```js
function sum(a: t.Number, n: t.Number): t.Number {
  return a + b
}
```

this is not ok (throws):

```js
function sum(a: number, n: number): number {
  return a + b
}
```

> If Tcomb syntax is Flow-compatible can we have both sides of the coin 

Yes, it would be great. Unfortunately all my attempts are failed. I suspect it's not possible but I'm open to suggestions.

All I could do is add support for primitive types:

- `string` -> `t.String`
- `number` -> `t.Number`
- `boolean` -> `t.Boolean`
- `Array` -> `t.Array`
- `Function` -> `t.Function`
- `Object` -> `t.Object`
- `any, mixed` -> `t.Any`

That would be easy, the real problem comes when you consider first-class types:

```js
const Person = t.struct({
  name: t.String
})

// Flow and TypeScript don't understand Person here
const foo = (person: Person) => ...
```

> Readme does not mention that "syntax-flow" and "transform-flow-strip-types" plugins are required.

Thanks for pointing out

**Comment by ivan-kleshnin** [comment]
Thanks for the answer.

> I suspect it's not possible but I'm open to suggestions.

Unfortunately, I don't even know Flow 😞  
But I also guess it's close to impossible until Flow exposes some kind of toolkit for that.

**Comment by gcanti** [comment]
Closing in favour of #11
