### ISSUE TITLE
Add support for EmptyTypeAnnotation

### ISSUE THREAD

**Issue by gcanti** [gcanti/babel-plugin-tcomb#150]

**Comment by omerzach** [comment]
We use empty to have Flow do exhaustiveness checking on sum types: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAzlgHYDGASnsQK4wYA8AKgHxgC8qYYA3mGIYAhhjrEAXGABE8YQBMAlmQDm0sAF8wAHx79BIsZJlz5eedIA0YeaOFSWmnXoFDR4qdLwAnb3G9WYAC2tMTCKnhSQt7KKpoA3OjY+GAAqsQ+XPpQit5CAHLCIVEYMarWMMIFRZEGZXEaiehQdJQYinBkYN54ZGbe6T4AFOI+UoPeAJQl9fx6PWLeXaPeAHQ5eRiFIWAA1DIH+yurldUhiRrNrRTtnd29-RMAJCMZ3k9SJOTUtAzME2xpnVYnNeMQEIoMBQABZgV4+J6rNxGSag3hgChVAiyOAKWLSCR6dH3RZdaQAGVxSlUgDICaSJYmYjImKnmAlE9E9Po+Cbw96rWwiSbxMDAYBgABi8CQAGsyIhiGAVojBcIwNCqmBkgQJnD5WQALRkBgwaz6g2tMw5MjmSYc0BM7E+PwBQnE3gLOhLGQAZTgIQw0JBCF6GDACD8qlW0hQHKtwj+bvdgb8SCGQwAHlI8EEcNhUZwOHwNJM+U9hXpLhogA

I'm trying to set up tcomb now but I get errors like
```
Module build failed: SyntaxError: [babel-plugin-tcomb] Unsupported type annotation: EmptyTypeAnnotation

  397 |
  398 |       default:
> 399 |         throw ((impossible: empty) => {})(tab);
      |                ^
  400 |     }
```

Is there any workaround until this issue is resolved?

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.3.25

**Comment by omerzach** [comment]
Awesome!
