### ISSUE TITLE
Recommended ordering issue

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#99]
I found out an issue when following the recommended order listed in [README.md under Setup](https://github.com/gcanti/babel-plugin-tcomb/blob/74b952146d80b77bfacef0a3ae67c8623f09f0d3/README.md#setup)

```js
"presets": ["es2015", "react", "stage-0"] // bad
"presets": ["stage-0", "react", "es2015"] // good
```

According to [@hzuu](https://github.com/hzoo) (See: [phabricator.babeljs.io/T7575](https://phabricator.babeljs.io/T7575)) The recommended ordering should be reversed:

```js
"presets": ["stage-0", "react", "es2015"] // bad
"presets": ["es2015", "react", "stage-0"] // good
```

Unless there is a reason related to tomb, would you be opposed to me putting in a PR to fix the ordering?

Also, the recommendation of ``passPerPreset: true`` breaks my build. From what I have read it is an experimental feature that is not 100% ready yet. Is it really required for tcomb to work correctly? I have not had any issues yet without it that I have seen (yet).

**Comment by volkanunsal** [comment]
@chrisblossom I was the one who suggested this order. It's the only one that worked for me using `passPerPreset`.

**Comment by gcanti** [comment]
@chrisblossom thanks for rising this issue, I'm not happy with that as well.

I'm afraid those requirements are the result of empiricism rather than science, I experienced many different ways of breaking the build, and it seems to depend on which presets AND plugins are installed. Also what breaks and how seems even change over time.

I'm ok with removing the current recommendations as long as we add a warning suggesting to try to tweak the preset order and / or the `passPerPreset` boolean if something goes wrong
